version: '3.7'

services:
  app:
    build: .
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      - PORT=8080
      - PG_USER=postgres
      - PG_PASSWORD=neverguess
      - PG_HOST=postgres
      - PG_PORT=5666
      - PG_DB=records
    ports:
      - 8080:8080
  db:
    image: postgres:11.12
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=neverguess
      - POSTGRES_USER=postgres
      - POSTGRES_DB=records
    ports:
      - 5666:5666
